In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

In [3]:
sqrt(441)


[1] 21

In [14]:
log(15)

[1] 2.70805

In [20]:
p<-matrix(1:12,nrow=3,ncol=4)
p

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [19]:
p

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [23]:
rownames(p)<-c("A","B","C")
p

[,1] [,2] [,3] [,4]
A 1    4    7    10  
B 2    5    8    11  
C 3    6    9    12

In [25]:
colnames(p)<-c("P","Q","R","S")
p

P Q R S 
A 1 4 7 10
B 2 5 8 11
C 3 6 9 12

In [26]:
p<-matrix(sample(1:12,12, replace = TRUE), nrow = 3)
p

[,1] [,2] [,3] [,4]
[1,]  3   9    8    10  
[2,] 10   3    6     1  
[3,]  4   8    1     2

In [27]:
x<-1:100
x

[1]   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
 [19]  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
 [37]  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
 [55]  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
 [73]  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
 [91]  91  92  93  94  95  96  97  98  99 100

In [28]:
q<-seq(2,100,2)
q

[1]   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36  38
[20]  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76
[39]  78  80  82  84  86  88  90  92  94  96  98 100